version: '3.8'
services:
  db:
    image: postgres:10-alpine
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  admin:
    image: adminer
    restart: always
    links:
      - db
    ports:
      - 8080:8080
